export const words  = [
    { word: "abajo", definition: "En una posición inferior." },
    { word: "abono", definition: "Sustancia con la que se fertiliza la tierra." },
    { word: "abren", definition: "Acción de abrir (ellos/ellas)." },
    { word: "acero", definition: "Aleación de hierro y carbono." },
    { word: "actos", definition: "Hechos, acciones." },
    { word: "adios", definition: "Despedida." },
    { word: "airea", definition: "Ventilar." },
    { word: "ajeno", definition: "Que pertenece a otro." },
    { word: "almas", definition: "Parte espiritual de los seres humanos." },
    { word: "altar", definition: "Mesa consagrada para el culto religioso." },
    { word: "amado", definition: "Persona querida." },
    { word: "amiga", definition: "Persona con la que se tiene una relación de amistad (femenino)." },
    { word: "anexo", definition: "Que va unido a otra cosa." },
    { word: "angel", definition: "Ser espiritual." },
    { word: "anima", definition: "Dotar de vida." },
    { word: "apodo", definition: "Nombre que se da a una persona en lugar del propio." },
    { word: "arcos", definition: "Estructuras en forma de curva." },
    { word: "ardor", definition: "Sensación de quemazón." },
    { word: "arena", definition: "Conjunto de partículas de rocas en las playas." },
    { word: "armar", definition: "Ensamblar piezas." },
    { word: "aseos", definition: "Lugares destinados a la higiene personal." },
    { word: "atlas", definition: "Libro de mapas." },
    { word: "autor", definition: "Persona que crea una obra." },
    { word: "aviso", definition: "Advertencia." },
    { word: "axiom", definition: "Proposición evidente que se acepta sin demostración." },
    { word: "bajar", definition: "Ir hacia abajo." },
    { word: "balon", definition: "Pelota grande utilizada en deportes." },
    { word: "barra", definition: "Pieza larga y delgada." },
    { word: "baste", definition: "Ser suficiente." },
    { word: "bingo", definition: "Juego de azar." },
    { word: "blusa", definition: "Prenda de vestir femenina." },
    { word: "bonos", definition: "Títulos de deuda." },
    { word: "botar", definition: "Lanzar algo con fuerza." },
    { word: "bravo", definition: "Valiente." },
    { word: "breve", definition: "De corta duración." },
    { word: "bueno", definition: "De calidad positiva." },
    { word: "burro", definition: "Animal de carga." },
    { word: "calma", definition: "Estado de tranquilidad." },
    { word: "campe", definition: "Dominio, superioridad." },
    { word: "campo", definition: "Terreno extenso fuera de la ciudad." },
    { word: "canal", definition: "Vía de comunicación o transporte de agua." },
    { word: "canon", definition: "Regla o precepto." },
    { word: "carro", definition: "Vehículo de cuatro ruedas." },
    { word: "casas", definition: "Viviendas." },
    { word: "cegar", definition: "Quitar la vista." },
    { word: "cielo", definition: "Firmamento." },
    { word: "clase", definition: "Conjunto de personas o cosas con características comunes." },
    { word: "clavo", definition: "Pieza metálica para fijar cosas." },
    { word: "coger", definition: "Asir o tomar algo." },
    { word: "comer", definition: "Ingerir alimentos." },
    { word: "comun", definition: "Que pertenece a todos." },
    { word: "conos", definition: "Figuras geométricas con una base circular y un vértice." },
    { word: "coral", definition: "Animal marino que forma colonias." },
    { word: "crear", definition: "Producir algo nuevo." },
    { word: "cruel", definition: "Que causa sufrimiento intencionadamente." },
    { word: "culpa", definition: "Responsabilidad por un daño causado." },
    { word: "curva", definition: "Línea que se aparta de la recta sin formar ángulos." },
    { word: "dardo", definition: "Proyectil pequeño y puntiagudo." },
    { word: "dados", definition: "Cubos utilizados en juegos de azar." },
    { word: "dejar", definition: "Permitir o abandonar." },
    { word: "denso", definition: "Que tiene mucha masa en relación con su volumen." },
    { word: "diana", definition: "Blanco circular para tiro." },
    { word: "diosa", definition: "Deidad femenina." },
    { word: "dolor", definition: "Sensación de malestar físico o emocional." },
    { word: "dosis", definition: "Cantidad de medicina que se toma de una vez." },
    { word: "duelo", definition: "Combate entre dos personas o dolor por la pérdida de un ser querido." },
    { word: "durar", definition: "Perdurar en el tiempo." },
    { word: "ecoan", definition: "Hacer eco, resonar." },
    { word: "echar", definition: "Hacer que algo vaya a parar a algún lugar." },
    { word: "elite", definition: "Grupo selecto o privilegiado." },
    { word: "emite", definition: "Lanzar o arrojar algo (él/ella)." },
    { word: "enano", definition: "Persona de muy baja estatura." },
    { word: "estar", definition: "Existir o hallarse en un lugar." },
    { word: "etnia", definition: "Grupo de personas con características culturales comunes." },
    { word: "exodo", definition: "Emigración de un pueblo o grupo de personas." },
    { word: "falda", definition: "Prenda de vestir femenina que cae desde la cintura." },
    { word: "falso", definition: "Que no es verdadero." },
    { word: "fases", definition: "Etapas de un proceso." },
    { word: "feliz", definition: "Que siente felicidad." },
    { word: "final", definition: "Última parte de algo." },
    { word: "firme", definition: "Sólido o estable." },
    { word: "flaco", definition: "De poca grasa corporal." },
    { word: "flojo", definition: "Que tiene poca fuerza o energía." },
    { word: "focos", definition: "Lámparas que concentran la luz en un punto." },
    { word: "forma", definition: "Aspecto exterior de algo." },
    { word: "fruta", definition: "Fruto comestible de ciertas plantas." },
    { word: "fuego", definition: "Combustión que despide calor y luz." },
    { word: "gafas", definition: "Lentes para corregir la vista." },
    { word: "gatos", definition: "Felinos domésticos." },
    { word: "girar", definition: "Dar vueltas sobre un eje." },
    { word: "golpe", definition: "Impacto de un cuerpo contra otro." },
    { word: "grano", definition: "Semilla de los cereales." },
    { word: "grasa", definition: "Sustancia untuosa." },
    { word: "guapo", definition: "De aspecto atractivo." },
    { word: "habla", definition: "Capacidad de expresarse mediante words." },
    { word: "hacer", definition: "Producir algo." },
    { word: "hecho", definition: "Acción realizada." },
    { word: "hilos", definition: "Filamentos largos y delgados." },
    { word: "honor", definition: "Consideración y respeto hacia una persona." },
    { word: "horas", definition: "Unidades de tiempo equivalentes a 60 minutos." },
    { word: "hueso", definition: "Cada una de las piezas duras que forman el esqueleto." },
    { word: "huevo", definition: "Óvulo de las aves." },
    { word: "idea", definition: "Representación mental de algo." },
    { word: "ideal", definition: "Que existe solo en la imaginación." },
    { word: "igual", definition: "Que no presenta diferencias." },
    { word: "invit", definition: "Atraer o inducir a alguien a hacer algo." },
    { word: "irnos", definition: "Marcharse (nosotros)." },
    { word: "japon", definition: "País insular del este de Asia." },
    { word: "jarra", definition: "Recipiente para líquidos." },
    { word: "juego", definition: "Actividad recreativa." },
    { word: "junto", definition: "Reunido en el mismo lugar." },
    { word: "karma", definition: "Consecuencia de las acciones de una persona." },
    { word: "kilos", definition: "Unidad de masa equivalente a 1000 gramos." },
    { word: "lapiz", definition: "Instrumento de escritura con mina de grafito." },
    { word: "latas", definition: "Recipientes metálicos." },
    { word: "lejos", definition: "A gran distancia." },
    { word: "libro", definition: "Conjunto de hojas con contenido escrito." },
    { word: "lucha", definition: "Combate o pelea." },
    { word: "lugar", definition: "Sitio o espacio." },
    { word: "luzca", definition: "Brillar o resplandecer (él/ella)." },
    { word: "macho", definition: "De sexo masculino." },
    { word: "mando", definition: "Control o autoridad sobre algo." },
    { word: "marea", definition: "Movimiento periódico del mar." },
    { word: "mejor", definition: "Superior a otra cosa." },
    { word: "menor", definition: "De menos importancia o tamaño." },
    { word: "meses", definition: "Unidades de tiempo equivalentes a aproximadamente 30 días." },
    { word: "mitad", definition: "Parte igual de un todo dividido en dos." },
    { word: "moda", definition: "Uso o costumbre que está en boga." },
    { word: "moral", definition: "Relacionado con las normas de conducta." },
    { word: "mover", definition: "Cambiar de lugar o posición algo." },
    { word: "mucho", definition: "Gran cantidad de algo." },
    { word: "mujer", definition: "Persona del sexo femenino." },
    { word: "multa", definition: "Sanción económica." },
    { word: "nadar", definition: "Desplazarse en el agua mediante movimientos corporales." },
    { word: "negro", definition: "Color más oscuro, ausencia de luz." },
    { word: "nieve", definition: "Agua congelada que cae de las nubes." },
    { word: "ninos", definition: "Personas de corta edad." },
    { word: "noble", definition: "De condición distinguida." },
    { word: "notar", definition: "Percibir o darse cuenta de algo." },
    { word: "nuevo", definition: "Recientemente creado o no usado." },
    { word: "nutre", definition: "Proveer de alimento (él/ella)." },
    { word: "oasis", definition: "Lugar con agua en el desierto." },
    { word: "ocaso", definition: "Puesta del sol." },
    { word: "oeste", definition: "Punto cardinal por donde se pone el sol." },
    { word: "ojear", definition: "Mirar de manera superficial." },
    { word: "omitir", definition: "Dejar de hacer algo." },
    { word: "orbita", definition: "Trayectoria curva alrededor de un cuerpo celeste." },
    { word: "organo", definition: "Parte del cuerpo que realiza una función específica." },
    { word: "osito", definition: "Diminutivo de oso." },
    { word: "otras", definition: "Distintas a las mencionadas." },
    { word: "ovalo", definition: "Figura geométrica similar a una elipse." },
    { word: "oyera", definition: "Percibir sonidos (subjuntivo, él/ella)." },
    { word: "pacto", definition: "Acuerdo entre dos o más partes." },
    { word: "palma", definition: "Parte interior de la mano." },
    { word: "parto", definition: "Acción de dar a luz." },
    { word: "patos", definition: "Aves acuáticas con pico ancho." },
    { word: "pelea", definition: "Lucha o combate." },
    { word: "pista", definition: "Lugar acondicionado para practicar deportes." },
    { word: "pluma", definition: "Estructura que cubre el cuerpo de las aves." },
    { word: "pobre", definition: "Que tiene poco dinero o recursos." },
    { word: "poema", definition: "Obra literaria en verso." },
    { word: "poder", definition: "Tener la capacidad de hacer algo." },
    { word: "prado", definition: "Terreno cubierto de hierba." },
    { word: "punto", definition: "Marca pequeña y circular." },
    { word: "queda", definition: "Permanecer en un lugar." },
    { word: "queja", definition: "Expresión de disgusto o descontento." },
    { word: "quema", definition: "Destruir con fuego." },
    { word: "quien", definition: "Pronombre relativo que se refiere a personas." },
    { word: "quiso", definition: "Tener el deseo (él/ella en pasado)." },
    { word: "rabia", definition: "Enfado muy grande." },
    { word: "ramas", definition: "Partes de un árbol que nacen del tronco." },
    { word: "rango", definition: "Categoría o nivel." },
    { word: "razon", definition: "Facultad de pensar o entender." },
    { word: "regar", definition: "Echar agua a las plantas." },
    { word: "resta", definition: "Operación matemática de sustracción." },
    { word: "reunir", definition: "Juntar a varias personas o cosas." },
    { word: "reyos", definition: "Plural de rey." },
    { word: "risas", definition: "Acción de reír." },
    { word: "robar", definition: "Quitar algo a alguien sin su permiso." },
    { word: "rodea", definition: "Estar alrededor de algo (él/ella)." },
    { word: "rompe", definition: "Partir en pedazos (él/ella)." },
    { word: "ronda", definition: "Grupo de personas que hacen guardia." },
    { word: "rosas", definition: "Flores de la planta del rosal." },
    { word: "rugir", definition: "Emitir un sonido fuerte y grave." },
    { word: "ruido", definition: "Sonido inarticulado y confuso." },
    { word: "sabor", definition: "Sensación que produce un alimento en el sentido del gusto." },
    { word: "sacar", definition: "Extraer algo de un lugar." },
    { word: "senda", definition: "Camino estrecho." },
    { word: "señal", definition: "Indicio que da a conocer algo." },
    { word: "serie", definition: "Conjunto de elementos que siguen un orden." },
    { word: "seria", definition: "Importante o de cuidado." },
    { word: "silba", definition: "Emitir un sonido agudo soplando (él/ella)." },
    { word: "sueno", definition: "Acto de dormir." },
    { word: "suelo", definition: "Superficie sobre la que se anda." },
    { word: "suena", definition: "Producir un sonido (él/ella)." },
    { word: "surge", definition: "Aparecer o manifestarse (él/ella)." },
    { word: "tacto", definition: "Sentido con el que se perciben las cosas mediante el contacto." },
    { word: "talon", definition: "Parte posterior del pie." },
    { word: "temer", definition: "Sentir miedo o recelo." },
    { word: "temor", definition: "Sensación de miedo." },
    { word: "tener", definition: "Poseer algo." },
    { word: "terco", definition: "Que se mantiene en su opinión o actitud con obstinación." },
    { word: "tesla", definition: "Unidad de densidad de flujo magnético." },
    { word: "tesoro", definition: "Conjunto de bienes valiosos." },
    { word: "texto", definition: "Conjunto de words escritas." },
    { word: "tocar", definition: "Poner en contacto las manos u otra parte del cuerpo con algo." },
    { word: "todos", definition: "Conjunto de personas o cosas sin excepción." },
    { word: "tomen", definition: "Coger o asir algo (ellos/ellas)." },
    { word: "topos", definition: "Mamíferos subterráneos pequeños." },
    { word: "torso", definition: "Parte superior del cuerpo humano." },
    { word: "trama", definition: "Argumento de una obra literaria o cinematográfica." },
    { word: "trato", definition: "Acuerdo o convenio." },
    { word: "trepa", definition: "Subir a un lugar alto (él/ella)." },
    { word: "trozo", definition: "Parte de algo que se ha dividido." },
    { word: "tumba", definition: "Lugar donde se entierra a una persona." },
    { word: "unica", definition: "Que es solo una y no hay otra igual." },
    { word: "vapor", definition: "Estado gaseoso de una sustancia." },
    { word: "varon", definition: "Persona del sexo masculino." },
    { word: "vasos", definition: "Recipientes para beber líquidos." },
    { word: "vello", definition: "Pelo fino y suave que cubre el cuerpo." },
    { word: "verbo", definition: "word que expresa una acción o un estado." },
    { word: "verso", definition: "Línea de un poema." },
    { word: "vesti", definition: "Vestimenta." },
    { word: "viaje", definition: "Traslado de un lugar a otro." },
    { word: "video", definition: "Grabación visual y sonora." },
    { word: "viento", definition: "Corriente de aire." },
    { word: "vista", definition: "Sentido con el que se perciben las imágenes." },
    { word: "voces", definition: "Sonidos que emiten las personas al hablar." },
    { word: "volar", definition: "Desplazarse por el aire." },
    { word: "yegua", definition: "Hembra del caballo." },
    { word: "yerba", definition: "Planta pequeña que crece en los campos." },
    { word: "yunta", definition: "Pareja de animales que se usan para arar." },
    { word: "zanah", definition: "Raíz comestible de color naranja." },
    { word: "zorro", definition: "Mamífero carnívoro de pelaje rojizo." },
    { word: "zurda", definition: "Que usa preferentemente la mano izquierda." }
];
